negative_adjectives = [
    "odious",
    "vile",
    "repugnant",
    "obnoxious",
    "abhorrent",
    "contemptible",
    "detestable",
    "despicable",
    "execrable",
    "abominable",
    "repulsive",
    "revolting",
    "disgusting",
    "loathsome",
    "horrid",
    "hideous",
    "grotesque",
    "grisly",
    "macabre",
    "monstrous",
    "diabolical",
    "infernal",
    "hellish",
    "fiendish",
    "satanic",
    "demonic",
    "mephitic",
    "noisome",
    "noxious",
    "miasmic",
    "pestilential",
    "vicious",
    "malicious",
    "malevolent",
    "sinister",
    "wicked",
    "evil",
    "nefarious",
    "depraved",
    "corrupt",
    "decadent",
    "degenerate",
    "debased",
    "perverted",
    "twisted",
    "sick",
    "pathetic",
    "pitiful",
    "miserable",
    "wretched",
    "sorry",
    "lamentable",
    "paltry",
    "low",
    "mean",
    "contemptuous",
    "disdainful",
    "scornful",
    "haughty",
    "arrogant",
    "cocky",
    "snobbish",
    "superior",
    "patronizing",
    "condescending",
    "snooty",
    "pretentious",
    "self-important",
    "egotistical",
    "narcissistic",
    "vain",
    "shallow",
    "superficial",
    "vacuous",
    "insipid",
    "boring",
    "tedious",
    "dull",
    "mundane",
    "prosaic",
    "uninspired",
    "unimaginative",
    "unoriginal",
    "trite",
    "clichéd",
    "hackneyed",
    "banal",
    "commonplace",
    "ordinary",
    "pedestrian",
    "unexceptional",
    "mediocre",
    "second-rate",
    "inferior",
    "substandard",
    "poor",
    "bad",
    "terrible",
    "awful",
    "dreadful",
    "horrible",
    "atrocious",
    "ghastly",
    "gruesome",
    "dire",
    "catastrophic",
    "disastrous",
    "calamitous",
    "cataclysmic",
    "apocalyptic",
    "doomed",
    "cursed",
    "accursed",
    "forsaken",
    "desolate",
    "barren",
    "wasteland",
    "devastated",
    "ruined",
    "destroyed",
    "despoiled",
    "desecrated",
    "blasphemous",
    "profane",
    "sacrilegious",
    "unholy",
    "unclean",
    "impure"]
negative_nouns = [
    "wretch",
    "scoundrel",
    "villain",
    "rogue",
    "miscreant",
    "rascal",
    "knave",
    "blackguard",
    "cad",
    "heel",
    "hound",
    "monster",
    "fiend",
    "devil",
    "demon",
    "beast",
    "brute",
    "barbarian",
    "savage",
    "thug",
    "goon",
    "bully",
    "hoodlum",
    "gangster",
    "mobster",
    "criminal",
    "outlaw",
    "pariah",
    "leper",
    "scum",
    "vermin",
    "pest",
    "insect",
    "worm",
    "serpent",
    "snake",
    "louse",
    "flea",
    "tick",
    "rat",
    "weasel",
    "skunk",
    "hyena",
    "jackal",
    "buzzard",
    "vulture",
    "parasite",
    "leech",
    "maggot",
    "reprobate",
    "degenerate",
    "pervert",
    "deviant",
    "maniac",
    "lunatic",
    "psychopath",
    "sociopath",
    "madman",
    "nutter",
    "lunatic",
    "berserker",
    "fanatic",
    "zealot",
    "bigot",
    "racist",
    "sexist",
    "homophobe",
    "xenophobe",
    "fascist",
    "tyrant",
    "dictator",
    "despot",
    "autocrat",
    "oppressor",
    "usurper",
    "traitor",
    "turncoat",
    "renegade",
    "quisling",
    "charlatan",
    "impostor",
    "fraud",
    "shyster",
    "quack",
    "swindler",
    "cheat",
    "con artist",
    "grifter",
    "scammer",
    "deceiver",
    "liar",
    "hypocrite",
    "phony",
    "fake",
    "imposter",
    "poser",
    "pretender",
    "snob",
    "elitist",
    "aristocrat",
    "plutocrat",
    "bourgeois",
    "capitalist",
    "profiteer",
    "exploiter",
    "parasite",
    "thief",
    "robber",
    "burglar",
    "bandit",
    "marauder",
    "pirate",
    "raider",
    "looter",
    "plunderer",
    "poacher",
    "rustler",
    "vandal",
    "saboteur",
    "terrorist",
    "anarchist",
    "rebel",
    "insurgent",
    "guerrilla",
    "radical",
    "extremist",
    "fanatic",
    "zealot",
    "heretic",
    "apostate",
    "infidel",
    "blasphemer",
    "atheist",
    "agnostic",
    "skeptic",
    "cynic",
    "pessimist",
    "defeatist",
    "coward",
    "weakling",
    "sissy"]
positive_adjectives = ['awesome',
                       'amazing',
                       'beautiful',
                       'brilliant',
                       'charming',
                       'confident',
                       'delightful',
                       'excellent',
                       'fantastic',
                       'gracious',
                       'happy',
                       'innovative',
                       'jolly',
                       'kind',
                       'lovely',
                       'marvelous',
                       'nice',
                       'optimistic',
                       'perfect',
                       'radiant',
                       'sensational',
                       'terrific',
                       'unforgettable',
                       'vibrant',
                       'wonderful',
                       'youthful',
                       'zesty']
positive_nouns = ['friend',
                  'mentor',
                  'champion',
                  'visionary',
                  'leader',
                  'hero',
                  'guide',
                  'advocate',
                  'inspiration',
                  'ally',
                  'partner',
                  'innovator',
                  'champion',
                  'ambassador',
                  'trailblazer',
                  'rockstar',
                  'guru',
                  'juggernaut',
                  'legend',
                  'icon', ]
actions = ["you're doing a wonderful job",
           "you're on the right track",
           "you're making great progress",
           "you're capable of amazing things",
           "you have what it takes",
           "you're strong and resilient",
           "you're a creative problem solver",
           "you're making a difference",
           "you're a valuable team member",
           "you'll go far",
           "you're an inspiration",
           "you're a true leader",
           "you're kind and compassionate",
           "you're making a positive impact",
           "you're destined for greatness",
           "you're capable of overcoming any challenge",
           "you're a fantastic listener",
           "you have a lot to offer",
           "you're a hard worker",
           "you're a fast learner",
           "you're determined and persistent",
           "you're innovative and resourceful",
           "you're a joy to work with",
           "you're a role model",
           "you have a bright future ahead",
           "nothing can hold you back",
           "you can do it",
           "the world needs your talents"]